name: CI

on:
  push:
    branches-ignore:
      - "gh-pages"

env:
  node_version: "14.x"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node_version }}
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: publish
        if: github.ref == 'refs/heads/master'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy --user "github-actions-bot <support+actions[bot]@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
